openapi: 3.0.0
info:
  version: '0.0.1'
  title: "HUFSPace API Documents"
  description: "한국외국어대학교 웹 페이지 프로젝트 API 문서"
servers:
  - description: "테스트 서버"
  - url: "http://52.78.2.40:8000/"
paths:
  /user:
    put:
      summary: 회원 정보 수정
      consumes: application/json
      produces: application/json
      parameters:
        - in: body
          name: body
          description: 회원 정보 수정
          required: true
          schema:
            type: object
            required:
              - nickname
            properties:
              nickname:
                type: string
                example: 도비

      responses:
        204:
          description: 회원 정보 정상 수정
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 204
                  message:
                    type: string
                    example: USER_INFO_UPDATED
        400:
          description: 이미 존재하는 닉네임
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: ALREADY_EXISTS

    delete:
      summary: 회원 탈퇴
      consumes: application/json
      produces: application/json
      responses:
        204:
          description: 회원 정상 탈퇴
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 204
                  message:
                    type: string
                    example: DEL_USER_SUCCESS


  /user/google:
    get:
      summary: 구글 소셜 로그인
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: 구글 소셜 로그인 정상 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: SUCCESS

  /user/kakao:
    get:
      summary: 카카오 소셜 로그인
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: 카카오 소셜 로그인 정상 완료
          content:
            appplication/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: SUCCESS


  /user/sign-up:
    post:
      summary: 회원 가입
      consumes: application/json
      produces: application/json
      parameters:
        - in: body
          name: body
          description: 회원 가입에 필요한 데이터 (webMail의 경우 @hufs.ac.kr 앞 부분까지만 입력)
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: 회원 가입 정상 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: SUCCESS
        400:
          description: 이미 존재하는 사용자
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: ALREADY_EXISTS

  /user/sign-out:
    post:
      summary: 로그아웃
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: 회원 가입 정상 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: SIGNED_OUT_SUCCESS
  /board/{id}:
    get:
      summary: 게시판 게시글 목록 조회
      consumes: application/json
      produces: application/json
      parameters:
        - in: path
          name: id
          description: 게시판 번호
          required: true
          example: 1
      responses:
        200:
          description: 게시글 정상 조회 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  post:
                    type: array
                    items:
                      $ref: "#/definitions/Post"
  /board/{id}/post:
    post:
      summary: 게시글 작성
      consumes: application/json
      produces: application/json
      parameters:
        - in: path
          name: id
          description: 게시판 번호
          required: true
          example: 1
        - in: body
          name: body
          description: 게시글 작성할 때 필요한 데이터 - url은 필수 X
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
                example: 글 제목
                required: true
              content:
                type: string
                example: 글 내용
                required: true
              url:
                type: array
                description: 삭제할 이미지 url 배열
                example: ["https://hufsweb.s3.ap-northeast-2.amazonaws.com/post/1614328320100sasa.jpg","https://hufsweb.s3.ap-northeast-2.amazonaws.com/post/1614328320100xz.jpg"]
                required: false
      responses:
        201:
          description: 게시글 작성
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 게시글 작성 완료
definitions:
  User:
    type: object
    required:
      - name
      - nickname
      - webMail
    properties:
      name:
        type: string
        example: 이태현
      nickname:
        type: string
        example: 도비
      webMail:
        type: string
        example: dlxogus0417
  Post:
    type: object
    properties:
      id:
        type: integer
        description: 글 번호
        example: 1
      title:
        type: string
        description: 글 제목
        example: 제목
      content:
        type: string
        description: 글 내용
        example: <p>안녕</p>
      like:
        type: integer
        description: 좋아요 개수
        exapmle: 32
      report:
        type: integer
        description: 신고 개수 / 5회 이상일 경우 숨김 처리
        example: 2
      createdAt:
        type: date
        description: 글 생성 날짜 및 시간
        example: 2021-03-14T06:21:29.000Z
      updatedAt:
        type: date
        description: 글 마지막으로 업데이트된 시간
        example: 2021-03-14T06:21:29.000Z
      boardId:
        type: integer
        description: 게시판 아이디
        example: 1
      userId:
        type: integer
        description: 글 작성한 유저의 아이디
        example: 1
      User:
        type: object
        properties:
          nickname:
            type: string
            description: 글 작성한 유저의 닉네임
            example: 하연

