openapi: 3.0.0
info:
  version: '0.0.1'
  title: "HUFSPace API Documents"
  description: "한국외국어대학교 웹 페이지 프로젝트 API 문서"
servers:
  - description: "테스트 서버"
  - url: "http://52.78.2.40:8000/"
paths:
  /user:
    get:
      summary: 회원 정보 조회
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: 회원 정보 정상 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example: { email: 0417taehyun@gmail.com, webMail: dlxogus0417@hufs.ac.kr, nickname: 도비 }
                  message:
                    type: string
                    example: ""           

    put:
      summary: 회원 정보 수정
      consumes: application/json
      produces: application/json
      parameters:
        - in: body
          name: body
          description: 회원 정보 수정
          required: true
          schema:
            type: object
            required:
              - nickname
            properties:
              nickname:
                type: string
                example: 도비
      responses:
        200:
          description: 회원 정보 정상 수정
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"
        409:
          description: 이미 존재하는 닉네임
          content:
            application/json:
              schema:
                $ref: "#/definitions/Invalid-response"

    delete:
      summary: 회원 탈퇴
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: 회원 정상 탈퇴
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"


  /user/sign-in/google:
    get:
      summary: 구글 소셜 로그인
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: 구글 소셜 로그인 정상 완료
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"

  /user/sign-in/kakao:
    get:
      summary: 카카오 소셜 로그인
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: 카카오 소셜 로그인 정상 완료
          content:
            appplication/json:
              schema:
                $ref: "#/definitions/Success-response"


  /user/sign-up:
    post:
      summary: 회원 가입
      consumes: application/json
      produces: application/json
      parameters:
        - in: body
          name: body
          description: 회원 가입에 필요한 데이터 (webMail의 경우 @hufs.ac.kr 앞 부분까지만 입력)
          required: true
          schema:
                type: object
                required:
                  - name
                  - nickname
                  - webMail
                properties:
                  name:
                    type: string
                    example: 이태현
                  nickname:
                    type: string
                    example: 도비
                  webMail:
                    type: string
                    example: dlxogus0417
      responses:
        200:
          description: 회원 가입 정상 완료
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"
        409:
          description: 이미 존재하는 닉네임
          content:
            application/json:
              schema:
                $ref: "#/definitions/Invalid-response"

  /user/sign-out:
    post:
      summary: 로그아웃
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: 로그아웃 정상 완료
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"

  /user/directory:
    get:
      summary: 스크랩을 위해 생성된 디렉토리 조회
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: 디렉토리 정상 조회 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example: [ { id: 4, name: 팁 }, { id: 6, name: 기타 } ]
                  message:
                    type: string
                    example: ""

    post:
      summary: 스크랩을 위해 디렉토리 생성
      consumes: application/json
      produces: application/json
      parameters:
        - in: body
          name: body
          description: 
          required: true
          schema:
            $ref: "#/definitions/Directory"   
      responses:
        200:
          description: 디렉토리 정상 생성 완료
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"
        409:
          description: 이미 존재하는 디렉토리 이름 
          content:
            application/json:
              schema:
                $ref: "#/definitions/Invalid-response"

    put:
      summary: 스크랩을 위해 생성된 디렉토리 수정
      consumes: application/json
      produces: application/json
      parameters:
        - in: body
          name: body
          description: 변경 될 디렉토리 이름
          required: true
          schema:
            $ref: "#/definitions/Directory"
        - in: query
          name: id
          description: 디렉토리 아이디
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 디렉토리 정상 생성 완료
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"
        409:
          description: 이미 존재하는 디렉토리 이름 
          content:
            application/json:
              schema:
                $ref: "#/definitions/Invalid-response"

    delete:
      summary: 스크랩을 위해 생성된 디렉토리 삭제
      consumes: application/json
      produces: application/json
      parameters:
        - in: query
          name: id
          description: 디렉토리 아이디
          required: true
          schema:
            type: integer     
      responses:
        200:
          description: 디렉토리 정상 삭제 완료
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"
        422:
          description: 디렉토리 아이디 쿼리 스트링으로 필요 
          content:
            application/json:
              schema:
                $ref: "#/definitions/Query-response"  
  
  /user/scrap:
    get:
      summary: 사용자가 스크랩한 게시글 조회
      consumes: application/json
      produces: application/json
      parameters:
        - in: query
          name: directoryId
          description: 디렉토리 아이디
          required: true
          schema:
            type: integer      
      responses:
        200:
          description: 스크랩 정상 조회 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example: [ { scrapId: 4, postId: 1, postTitle: 첫 번째 게시글 }, { scarpId: 5, postId: 2, postTitle: 두 번째 게시글 } ]
                  message:
                    type: string
                    example: ""
        422:
          description: 디렉토리 아이디 쿼리 스트링으로 필요 
          content:
            application/json:
              schema:
                $ref: "#/definitions/Query-response"

    post:
      summary: 게시글 스크랩
      consumes: application/json
      produces: application/json
      parameters:
        - in: query
          name: postId
          description: 게시글 아이디
          required: true
          schema:
            type: integer      
      responses:
        200:
          description: 정상 스크랩 완료
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"
        409:
          description: 이미 스크랩한 게시글
          content:
            application/json:
              schema:
                $ref: "#/definitions/Invalid-response"
        422:
          description: 게시글 아이디 쿼리 스트링으로 필요 
          content:
            application/json:
              schema:
                $ref: "#/definitions/Query-response"

    put:
      summary: 사용자가 스크랩한 게시글 디렉토리 이동
      consumes: application/json
      produces: application/json
      parameters:
        - in: query
          name: postId
          description: 게시글 아이디
          required: true
          schema:
            type: integer
        - in: query
          name: directoryId
          description: 디렉토리 아이디
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 스크랩 정상 조회 완료
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"
        422:
          description: 게시글 아이디와 디렉토리 아이디 쿼리 스트링으로 필요 
          content:
            application/json:
              schema:
                $ref: "#/definitions/Query-response"

    delete:
      summary: 사용자 스크랩 삭제
      consumes: application/json
      produces: application/json
      parameters:
        - in: query
          name: id
          description: 스크랩 아이디
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 스크랩 정상 조회 완료
          content:
            application/json:
              schema:
                $ref: "#/definitions/Success-response"
        422:
          description: 스크랩 아이디 쿼리 스트링으로 필요 
          content:
            application/json:
              schema:
                $ref: "#/definitions/Query-response"
  /board/{id}:
    get:
      summary: 게시판 게시글 목록 조회
      consumes: application/json
      produces: application/json
      parameters:
        - in: path
          name: id
          description: 게시판 번호
          required: true
          example: 1
      responses:
        200:
          description: 게시글 정상 조회 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  post:
                    type: array
                    items:
                      $ref: "#/definitions/Post"
  /board/{id}/post:
    post:
      summary: 게시글 작성
      consumes: application/json
      produces: application/json
      parameters:
        - in: path
          name: id
          description: 게시판 번호
          required: true
          example: 1
        - in: body
          name: body
          description: 게시글 작성할 때 필요한 데이터 - url은 필수 X
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
                example: 글 제목
                required: true
              content:
                type: string
                example: 글 내용
                required: true
              url:
                type: array
                description: 삭제할 이미지 url 배열
                example: ["https://hufsweb.s3.ap-northeast-2.amazonaws.com/post/1614328320100sasa.jpg","https://hufsweb.s3.ap-northeast-2.amazonaws.com/post/1614328320100xz.jpg"]
                required: false
      responses:
        201:
          description: 게시글 작성
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 게시글 작성 완료


definitions:
  # 성공
  Success-response:
    type: object
    properties:
      data:
        type: object
        example: ""
      message:
        type: string
        example: ""

  # 이미 존재하는 데이터
  Invalid-response:
    type: object
    properties:
      data:
        example: ""
      message:
        type: string
        example: INVALID

  # 쿼리 스트링 누락
  Query-response:
    type: object
    properties:
      data:
        example: ""
      message:
        type: string
        example: QUERY

  # 디렉토리 Body Request
  Directory:
    type: object
    required:
      - name
    properties:
      nickname:
        type: string
        example: 학교생활 팁 모음
  Post:
    type: object
    properties:
      id:
        type: integer
        description: 글 번호
        example: 1
      title:
        type: string
        description: 글 제목
        example: 제목
      content:
        type: string
        description: 글 내용
        example: <p>안녕</p>
      like:
        type: integer
        description: 좋아요 개수
        exapmle: 32
      report:
        type: integer
        description: 신고 개수 / 5회 이상일 경우 숨김 처리
        example: 2
      createdAt:
        type: date
        description: 글 생성 날짜 및 시간
        example: 2021-03-14T06:21:29.000Z
      updatedAt:
        type: date
        description: 글 마지막으로 업데이트된 시간
        example: 2021-03-14T06:21:29.000Z
      boardId:
        type: integer
        description: 게시판 아이디
        example: 1
      userId:
        type: integer
        description: 글 작성한 유저의 아이디
        example: 1
      User:
        type: object
        properties:
          nickname:
            type: string
            description: 글 작성한 유저의 닉네임
            example: 하연