# name: Node CI / CD
# on :
#   push:
#     branches: [ main ]
# jobs:
#   build:
#     name: Deploy
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [ 15.x ]
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v2

#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
      
#       - name: Npm Install
#         run: npm install
            
#       - name: Access Amazon EC2
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_EC2_SECRET_ACCESS_KEY_ID }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Deploy
#         run: |
#           aws deploy create-deployment \
#             --application-name ${{ secrets.AWS_CODE_DEPLOY_APP_NAME }} \
#             --deployment-config-name ${{ secrets.AWS_CODE_DEPLOY_CONFIG_TYPE }} \
#             --deployment-group-name ${{ secrets.AWS_CODE_DEPLOY_GROUP_NAME }} \
#             --github-location repository=${{ github.repository }},commitId=${{ github.sha }}